# Generated by Django 3.1.5 on 2021-01-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
