# Generated by Django 3.1.5 on 2021-01-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20210119_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='candidates/'),
        ),
    ]
