# Generated by Django 3.1.5 on 2021-01-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210119_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
